name: SonarCloud Analysis main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:12.0.2
        env:
          MARIADB_ROOT_PASSWORD: uvlhub_root_password
          MARIADB_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -u root -puvlhub_root_password || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    env:
      MARIADB_ROOT_PASSWORD: uvlhub_root_password
      MARIADB_DATABASE: uvlhubdb_test
      MARIADB_TEST_DATABASE: uvlhubdb_test
      MARIADB_USER: uvlhub_user
      MARIADB_PASSWORD: uvlhub_password
      MARIADB_HOSTNAME: 127.0.0.1
      MARIADB_PORT: 3306
      FLASK_ENV: testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov selenium

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Start the project (backend)
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &
          sleep 5  # ðŸ‘ˆ Espera 5s para asegurarse de que el servidor arranca

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=xml

      - name: Install SonarCloud Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip
          echo "${{ github.workspace }}/sonar-scanner-4.7.0.2747-linux/bin" >> $GITHUB_PATH

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=egc_tennis-hub \
            -Dsonar.organization=egc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.sources=. \
            -Dsonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**
